### PR TITLE
Use juju/errors instead of go/errors, not include assert/log/trace pa…

### PR DESCRIPTION
**Pull request by qiuyesuifeng**
…ckage

### CODE REVIEW

**Comment by qiuyesuifeng** [comment]
@siddontang  how about this pr?

**Comment by qiuyesuifeng** [comment]
@ngaut  any suggestion?

**Comment by ngaut** [comment]
LGTM

**Comment by siddontang** [comment]
Should we supply some helper function to check error equal like ZkErrorEqual？

**Comment by qiuyesuifeng** [comment]
yeah, is it better to add helper func in ngaut/zkhelper package?

**Comment by siddontang** [comment]
no，I think we can use a error2 pkg

**Comment by qiuyesuifeng** [comment]
this error package has no use, should we directly use it?
also trace/testing/log packages have no use, remove them?

**Comment by siddontang** [comment]
maybe yes.

**Pull request merged**
